src/Entity/Menu.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MenuRepository")
 */
class Menu
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $id_parent;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $redirect_to_url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $redirect_to;

    /**
     * @ORM\Column(type="text")
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdParent(): ?int
    {
        return $this->id_parent;
    }

    public function setIdParent(?int $id_parent): self
    {
        $this->id_parent = $id_parent;

        return $this;
    }

    public function getRedirectToUrl(): ?string
    {
        return $this->redirect_to_url;
    }

    public function setRedirectToUrl(?string $redirect_to_url): self
    {
        $this->redirect_to_url = $redirect_to_url;

        return $this;
    }

    public function getRedirectTo(): ?string
    {
        return $this->redirect_to;
    }

    public function setRedirectTo(?string $redirect_to): self
    {
        $this->redirect_to = $redirect_to;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

templates/base.html.twig
{# Výpis zpráv. #}
<html lang="cs-cz">
<head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Albert Patera#{{ block('title') }}</title>

    <!-- include summernote css/js -->
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script>


</head>
<article>

    <header>
        <h1 id="header" class="text-center display-1 text-info" style="text-transform: uppercase">website administration</h1>
        <hr>
            <ul class="nav">
                <li title="home" style="display:block"><a href="/" class="nav nav-link text-secondary"><span class="fa fa-home"></span> </a> </li>
                {% for item in menu %}

                    {% if item.idParent > 0 %}

                        <li id="{{ item.name|lower }}_{{ item.id }}" class="dis nav-item" style="display: block"><a  title="{{ item.description }}" class="nav-link text-secondary" href="{% if item.redirectToUrl != NULL %} 'http://' {{ item.redirectToUrl }}" target="_blank {% else %}{{ item.redirectTo }}{% endif %}">{{ item.name }}</a></li>
                    {% else %}
                        <li  id="{{ item.name|lower }}_{{ item.id }}" class="nav-item" style="display: inline-block; list-style-type: none" title="{{ item.description }}"><a class="nav-link" id="{{ item.id }}-{{ item.name }}" title="{{ item.description }}" href="{{ item.redirectTo }}">{{ item.name }}</a> </li>

                    {% endif %}

                {%  endfor%}
            </ul>
        <hr>

    </header>
    <section>
        <div class="container-fluid">

            {% block body %}{% endblock %} {# Vložení obsahu do šablony. #}
        </div>

    </section>
</article>
</html>

{% block javascripts %}
    <script src="/js/sticky_menu/jquery.sticky.js"></script>
    <script>
        $(document).ready(function() {
            $('.summernote').summernote();
            $("header").sticky({topSpacing:0});
        });
    </script>
{% endblock %}